networks:
  monitoring:
    driver: bridge

services:
  prometheus-node-exporter:
    image: prom/node-exporter:v1.4.0
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - "9100"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  gpu-exporter:
    image: nvidia/dcgm-exporter:1.7.2-2.0.0-rc.8-ubuntu18.04
    container_name: gpu-exporter
    restart: unless-stopped
    expose:
      - "9400"
    networks:
      - monitoring
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/shared/prometheus_data:/prometheus # for guanine
      #- /service_data/prometheus_data:/prometheus # for glycine
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 15999:9090 # for guanine
      #- 16002:9090 # for glycine

  #my-app:
  #  image: my-app:0.1.0
  #  container_name: app
  #  build:
  #    context: .
  #    dockerfile: app.Dockerfile
  #  ports:
  #    - 16001:80
  #  networks:
  #    - monitoring
